### PR TITLE
Feature/feather workflows

### LINKED ISSUE #47: Universe Feather alpha demo landing view build & UI
**Description**
Universe Feather alpha demo landing view build & UI.

**Tasks**
- [x] Build & UI for Universe Feather alpha demo landing view

**Content**
- User opens their Chrome or Brave browser, navigates, and sees a welcome landing page that reads...

[Universe logo]
"Welcome to Universe"
"Your Universe Feather device is not connected." [bold type]
"Please follow the setup instructions on that came with your device or click here for instructions."

### LINKED ISSUE #48: Universe Feather alpha demo online instructions view build & UI
**Description**
Universe Feather alpha demo online instructions view build & UI.

**Tasks**
- [x] Build & UI for Universe Feather alpha demo online instructions view for new users.
- [x] Build & UI for Universe Feather alpha demo online instructions view for existing users.

**Content**

#### Online Instructions for new Universe users
User chooses to read online instructions
[Universe icon] + [Bluetooth icon]
[Headline] "Connect your Universe Feather to your laptop" [bold type].
"Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
"Press the button to turn on Universe Feather device"
"Connect device"
"Go to your Bluetooth setting and choose Feather Device"
"Sign up"
"Go back to your web browser and sign up for Universe"

#### Online Instructions for existing Universe users
User chooses to read online instructions
[Universe icon] + [Bluetooth icon]
[Headline] "Connect your Universe Feather to your laptop" [bold type].
"Turn on device" — ›››››› [[[[[ This is an unknown ]]]]] ‹‹‹‹‹‹ —
"Press the button to turn on Universe Feather device"
"Connect device"
"Go to your Bluetooth setting and choose Feather Device"
"Confirm device"
"Go back to your web browser and confirm device"

### PR DESCRIPTION
**Pull request by modkaffes**
This adds feather onboarding views along with instructions views for new and returning users.

Closes #47, closes #48

### CODE REVIEW

**Comment by guylepage3** [comment]
@modkaffes let me know when this is ready. Thank you.

**Comment by modkaffes** [comment]
@guylepage3 it’s ready to merge as it is, only issue I have is versioning. Please, let me know so I can fix the conflict.

What’s the correct next version to be pushed? Right now on `develop` it’s [1.0.1-alpha.1](https://github.com/universelabs/universe-webapp/blob/develop/client/package.json#L3), so given that a feature was added in this PR, should the next version be `1.1.0-alpha.1`?

Also, what about the [server version](https://github.com/universelabs/universe-webapp/blob/develop/package.json#L3)? Is it independent than the client?

**Comment by guylepage3** [comment]
@modkaffes, yes.. that is correct this feature will make the client `v1.1.0-alpha.1`.

Yes, the server is independent from the client.

**Comment by modkaffes** [comment]
@guylepage3 perfect, I’m fixing and merging it.

**Pull request merged**
